version: '2'

services:
  llm_wordle:
    build:
      context: ../
      dockerfile: dockers/Dockerfile.dev
    user: root
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../.data/llm_wordle/logs:/var/log/llm_wordle
      - ../.data/llm_wordle/uploads:/var/uploads
      - ../:/opt/llm_wordle:ro
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
        default:
        internal:
    environment:
      - ADMIN_PASSWORD=admin
      - PREFERRED_URL_SCHEME=http
      - REDIS_URL=redis://cache:6379/0
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - DATABASE_PROTOCOL=mysql+pymysql
      - DATABASSE_USER=llm_wordle
      - DATABASE_PASSWORD=llm_wordle
      - DATABASE_HOST=db
      - DATABAE_PORT=
      - DATABASE_NAME=llm_wordle
      - PUBLIC_SETTINGS_FILE=public_settings.dev.json
      - ADMIN_SETTINGS_FILE=admin_settings.json
      - WORKERS=1
      - LOG_FOLDER=/var/log/llm_wordle

  caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ../Caddyfile.dev:/etc/caddy/Caddyfile
      - ../.data/caddy/data:/data
      - ../.data/caddy/config:/config

  db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=llm_wordle
      - MYSQL_USER=llm_wordle
      - MYSQL_PASSWORD=llm_wordle
      - MYSQL_DATABASE=llm_wordle
    volumes:
      - ../.data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  cache:
    image: redis:4
    restart: always
    volumes:
    - ../.data/redis:/data
    networks:
        internal:
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

networks:
    default:
    internal:
        internal: true
