FROM python:3.10-slim-bookworm as build

WORKDIR /opt/llm_wordle

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libffi-dev \
        libssl-dev \
        git \
        nodejs \
        npm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && python -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

COPY . /opt/llm_wordle

RUN pip install --no-cache-dir -r requirements.txt
RUN /bin/bash build.sh

FROM python:3.10-slim-bookworm as release
WORKDIR /opt/llm_wordle

# hadolint ignore=DL3008


COPY --chown=1001:1001 --from=build /opt/llm_wordle/app/ /opt/llm_wordle/app/
COPY --chown=1001:1001 --from=build /opt/llm_wordle/conf/ /opt/llm_wordle/conf/
COPY --chown=1001:1001 --from=build /opt/llm_wordle/templates /opt/llm_wordle/templates
COPY --chown=1001:1001 --from=build /opt/llm_wordle/public_settings.dev.json /opt/llm_wordle/public_settings.dev.json
COPY --chown=1001:1001 --from=build /opt/llm_wordle/admin_settings.dev.json /opt/llm_wordle/admin_settings.dev.json
COPY --chown=1001:1001 --from=build /opt/llm_wordle/logging.yml /opt/llm_wordle/logging.yml
COPY --chown=1001:1001 --from=build /opt/llm_wordle/gunicorn.conf.py /opt/llm_wordle/gunicorn.conf.py


RUN useradd \
    --no-log-init \
    --shell /bin/bash \
    -u 1001 \
    llm_wordle \
    && mkdir -p /var/log/llm_wordle \
    && chown -R 1001:1001 /var/log/llm_wordle /opt/llm_wordle/app
    

COPY --chown=1001:1001 --from=build /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

USER 1001
EXPOSE 8000
ENTRYPOINT ["gunicorn","app.admin.main:admin_app"] 
#, "--log-config", "logging.yml"]