"""RESTful API calls to remote LLMs."""
# Standard library imports.
import os
from typing import List
from logging import getLogger

# Third-party imports.
from fastapi import HTTPException
from starlette.status import HTTP_500_INTERNAL_SERVER_ERROR
import aiohttp
from uuid import uuid4

log = getLogger("generator")


async def generate_text(preprompt: str, prompt: str, model: str) -> str:
    """Generate text from a prompt using the EleutherAI GPT-NeoX-20B model.

    Arguments:
        preprompt: The preprompt to generate text from.
        prompt: The prompt to generate text from.

    Raises:
        ValueError: If the Vanilla Neox API key is not set.
        HTTPError: If the EleutherAI API returns a non-200 HTTP status code.

    Returns:
        str: Text generated by the prompt.
    """
    url = os.environ.get('LLMV_ROUTER_URL')
    if url is None:
        raise ValueError('LLM Verification Router URL is not set')
    route = url + '/chat/generate'
    token = os.environ.get('LLMV_ROUTER_TOKEN')
    if token is None:
        raise ValueError('LLM Verification Router token is not set')
    # not needed for this type of deployment.
    uuid = str(uuid4())
    log.info(f'Received text generation request for prompt "{prompt}" for model "{model}"')
    # Load the Vanilla Neox API key from the config file.
    async with aiohttp.ClientSession() as session:
        async with session.post(url=route,
                        headers={'Authorization': f'Bearer {token}'},
                        json={"uuid": uuid, 'prompt': prompt, "preprompt" : preprompt, "model": model}) as raw_response:
    
            if raw_response.status == 200:
                json_response = await raw_response.json()
                log.info(json_response)

                if json_response.get('error') is not None:
                    log.error(f"Error generating: {json_response['error']}")
                    raise HTTPException(
                        HTTP_500_INTERNAL_SERVER_ERROR, "Model Error"
                    )
                return json_response['generation']

            elif 400 <= raw_response.status <= 599:
                # ... raise an error.
                log.error(f"Error generating: {raw_response.status}")
                raise HTTPException(HTTP_500_INTERNAL_SERVER_ERROR, f'LLM Router API returned error status code {raw_response.status}: ')
            # ... Otherwise, if it's an unrecognized HTTP status code, then...
            else:
                log.error(f"Error generating: {raw_response.status}")
                raise HTTPException(HTTP_500_INTERNAL_SERVER_ERROR, f'LLM Router API returned unrecognized status code {raw_response.status}: ')


async def get_models() -> List[str]:
    url = os.environ.get('LLMV_ROUTER_URL')
    if url is None:
        raise ValueError('LLM Verification Router URL is not set')
    route = url + '/chat/models'
    token = os.environ.get('LLMV_ROUTER_TOKEN')
    if token is None:
        raise ValueError('LLM Verification Router token is not set')
    log.info(f"Getting models from {route}")
    async with aiohttp.ClientSession() as session:
        async with session.post(url=route,
                        headers={'Authorization': f'Bearer {token}'}) as raw_response:
    
            if raw_response.status == 200:
                json_response = await raw_response.json()
                if 'error' in json_response:
                    log.error(f"Error generating: {json_response['error']}")
                    raise HTTPException(
                        HTTP_500_INTERNAL_SERVER_ERROR, "Model Error", headers={"Retry-After": str(60000)}
                    )
                return json_response['models']
    
            elif 400 <= raw_response.status <= 599:
                # ... raise an error.
                log.error(f"Error generating: {raw_response.status}")
                raise HTTPException(HTTP_500_INTERNAL_SERVER_ERROR, f'LLM Router API returned error status code {raw_response.status}: ')
            # ... Otherwise, if it's an unrecognized HTTP status code, then...
            else:
                log.error(f"Error generating: {raw_response.status}")
                raise HTTPException(HTTP_500_INTERNAL_SERVER_ERROR, f'LLM Router API returned unrecognized status code {raw_response.status}: ')
    
    